// The Halo Deck — a fixed, symbolic deck the oracle draws from. Titles are
// stable so they recur across a person's life and accrue personal meaning;
// the *interpretation* changes with the question and the moment, never the
// name. The "essence" is a short anchor that keeps each card's meaning
// consistent every time it appears. Themes drive illustration selection.

import type { CardTheme } from "../types";

export type HaloElement = "Fire" | "Water" | "Earth" | "Air" | "Spirit";

export interface HaloCard {
  title: string;
  theme: CardTheme;
  symbol: string;
  /** A cryptic, poetic anchor — like a whisper from an oracle. */
  essence: string;
  element: HaloElement;
  number: number;
  color: string;
  reflection: string;
}

export const HALO_DECK: HaloCard[] = [
  {
    title: "The Long Road",
    theme: "guidance_decision",
    symbol: "A dirt road disappearing into fog, with footprints that seem to appear just ahead of the walker, not behind them.",
    essence: "The path is not found — it is made by the feet that trust it.",
    element: "Earth",
    number: 7,
    color: "Muted green-grey",
    reflection: "If you follow this road to its end, what will you have left behind without noticing?",
  },
  {
    title: "The Open Gate",
    theme: "hope_abundance",
    symbol: "A wooden gate standing alone in an open field, no fence attached to either side. Beyond it, the air shimmers as if the world on the other side is slightly different.",
    essence: "The gate was never locked — you were the one who kept looking for the key.",
    element: "Air",
    number: 3,
    color: "Gold-tinged white",
    reflection: "If you step through without knowing what is on the other side, who will you become on the way?",
  },
  {
    title: "The Distant Lantern",
    theme: "guidance_decision",
    symbol: "A single light far across a dark valley — too far to read by, but close enough to walk toward. The ground between here and there is invisible.",
    essence: "You do not need to see the whole path — only the next step toward the light.",
    element: "Fire",
    number: 11,
    color: "Amber against deep black",
    reflection: "If the lantern were suddenly gone, would you still walk in that direction?",
  },
  {
    title: "The River Keeps Moving",
    theme: "release_change",
    symbol: "A wide river at night, carrying leaves and branches — all of them moving, none of them struggling. The moon lays a silver road across the surface that nothing can walk on.",
    essence: "You are not the one who moves the water. You are the one who learns to float.",
    element: "Water",
    number: 4,
    color: "Deep blue-grey",
    reflection: "What would you stop fighting if you truly believed you were already being carried?",
  },
  {
    title: "Winter Roots",
    theme: "quiet_strength",
    symbol: "A bare tree in snow — nothing above ground, but beneath the frost, roots are spreading wider than the tree ever was. The soil is warm where they reach.",
    essence: "The most important growth happens when no one is watching — not even you.",
    element: "Earth",
    number: 9,
    color: "White-grey with deep brown beneath",
    reflection: "If you could not see your own progress for one full year, would you still trust the work?",
  },
  {
    title: "The Sleeping Seed",
    theme: "hope_abundance",
    symbol: "A single seed buried in dark soil — not yet cracked, not yet watered. Above it, the sun is rising, but the seed cannot see it yet.",
    essence: "What is not yet visible is not yet absent.",
    element: "Earth",
    number: 8,
    color: "Deep brown with a thread of gold",
    reflection: "If the seed could speak, would it call itself dead — or waiting?",
  },
  {
    title: "The Gathering Harvest",
    theme: "hope_abundance",
    symbol: "A stone table at the edge of a wheat field, piled with fruit no one remembers planting. The wind carries the scent of grain and something older — an offering left for no one in particular.",
    essence: "What was forgotten still ripened. What was abandoned still bore fruit.",
    element: "Earth",
    number: 18,
    color: "Burnished gold and deep ochre",
    reflection: "What have you stopped tending — that has been quietly growing without you?",
  },
  {
    title: "The Turning Door",
    theme: "release_change",
    symbol: "A heavy wooden door, half open, light pouring from the side you are leaving and shadow pooling on the side you are entering. The hinges are silent, as if the door has been turning for longer than you noticed.",
    essence: "The door does not close behind you — it turns. And what you hear on the other side is the sound of your own footsteps, already there.",
    element: "Spirit",
    number: 13,
    color: "Warm bronze fading into cool violet",
    reflection: "What is the room you keep returning to in your mind — the one you have already left?",
  },
  {
    title: "The Quiet Compass",
    theme: "guidance_decision",
    symbol: "A small, old compass — but the needle does not point north. It points toward something only the owner can feel. The glass is cracked, but the needle is steady.",
    essence: "The direction you need is not on any map. It is felt before it is known.",
    element: "Spirit",
    number: 5,
    color: "Silver and deep blue",
    reflection: "If your inner compass pointed toward a place that did not exist yet — would you still follow it?",
  },
  {
    title: "The Last Ember",
    theme: "quiet_strength",
    symbol: "A fire pit at dawn, all logs turned to ash — except one coal, still glowing faintly orange at its center. No one is tending it. The wind has not found it yet.",
    essence: "What remains is not what survived the fire — it is what the fire could not finish.",
    element: "Fire",
    number: 15,
    color: "Burnt orange in a field of ash-grey",
    reflection: "If this ember is the last warmth you carry — what would you choose to light with it?",
  },
  {
    title: "The Unfinished Horizon",
    theme: "hope_abundance",
    symbol: "A vast sky where the horizon line is half-drawn — as if a painter stopped mid-stroke. The land fades into mist where the line ends, and beyond it, colors exist that have no name yet.",
    essence: "The story has not stopped — the hand that writes it is only resting.",
    element: "Air",
    number: 17,
    color: "Lavender bleeding into unfinished white",
    reflection: "If the ending has not been written — who told you it was too late to change the middle?",
  },
  {
    title: "The Weight of Becoming",
    theme: "release_change",
    symbol: "A chrysalis hanging from a bare branch, too heavy for the twig — yet the twig holds. Inside, something is neither caterpillar nor moth. It is shapeless, and it is everything.",
    essence: "What feels like breaking apart is the old shape making room for what has no name yet.",
    element: "Earth",
    number: 16,
    color: "Dark amber and bruised violet",
    reflection: "What if the heaviness you carry is not a burden — but the weight of something trying to be born?",
  },
  {
    title: "The Bridge Being Built",
    theme: "guidance_decision",
    symbol: "A stone bridge stretching across a gorge — half finished. The last stones are floating in midair, not yet laid, as if waiting for someone to place them by walking across.",
    essence: "The bridge does not exist until you step where the stones are not.",
    element: "Earth",
    number: 19,
    color: "Grey stone with threads of copper",
    reflection: "What would you build if you did not need to see the other side first?",
  },
  {
    title: "The Place Between",
    theme: "release_change",
    symbol: "A narrow corridor with no doors — behind, a room full of firelight; ahead, a room full of starlight. The corridor itself is neither warm nor cold, neither dark nor bright. A single moth floats through it, unbothered.",
    essence: "You are not lost. You are in the hallway — and hallways do not last forever.",
    element: "Spirit",
    number: 12,
    color: "Twilight grey — neither silver nor shadow",
    reflection: "If you could not go back and could not yet go forward — what would you notice about where you stand right now?",
  },
  {
    title: "The Path With No Shortcut",
    theme: "guidance_decision",
    symbol: "A spiraling mountain trail that passes the same cliff face three times at different heights. Each pass reveals the same valley below — but each time, the valley looks smaller.",
    essence: "The path circles not because it is lost, but because some distances can only be crossed by climbing.",
    element: "Earth",
    number: 20,
    color: "Slate blue and weathered stone",
    reflection: "What have you circled back to — that looks different now that you are higher?",
  },
  {
    title: "The Light Beyond",
    theme: "hope_abundance",
    symbol: "A tunnel carved through solid rock. The walls are wet and dark. Far ahead, not sunlight — but a glow without source, the color of something remembered rather than seen.",
    essence: "The light at the end is not the sun. It is the memory of warmth, reminding you that you have felt it before.",
    element: "Fire",
    number: 22,
    color: "Distant gold behind deep black",
    reflection: "If the light you are moving toward is a memory — what moment does it come from?",
  },
  {
    title: "The Slow Arrival",
    theme: "exhaustion_rest",
    symbol: "A traveler's boots placed neatly at the door of a house they have not yet entered. Inside, a chair is already pulled out. A cup of water is poured. No one is visible — but someone knew they were coming.",
    essence: "You have been arriving longer than you know. The door has been open for some time.",
    element: "Water",
    number: 2,
    color: "Warm clay and soft candlelight",
    reflection: "What if you have already arrived — and the only thing left is to sit down?",
  },
  {
    title: "The Orchard",
    theme: "hope_abundance",
    symbol: "An orchard of ancient fruit trees in full bloom — but the ground beneath is covered with fruit from seasons no one was there to harvest. New blossoms grow from the rot of the old.",
    essence: "What was not gathered did not go to waste — it fed the roots for what comes next.",
    element: "Earth",
    number: 6,
    color: "Deep green canopy over fallen gold",
    reflection: "What have you let fall — that is now feeding something you cannot see yet?",
  },
  {
    title: "The Returning Tide",
    theme: "release_change",
    symbol: "A shoreline at the exact moment between tides — the sand is dark and smooth, marked by the ghost-shapes of shells the water carried away. The next wave has not arrived, but the sand is already leaning toward it.",
    essence: "What left you did not leave you. It is circling back in a shape you will not recognize at first.",
    element: "Water",
    number: 14,
    color: "Wet silver and midnight blue",
    reflection: "If what you lost returned wearing a different face — would you still know it?",
  },
  {
    title: "The Empty Chair",
    theme: "feeling_unseen",
    symbol: "A wooden chair at a table set for two. One plate is full, the other is clean and empty. The window is open, and the curtain moves as if someone just passed through.",
    essence: "The absence is not proof that no one came. It is proof that you are still setting a place.",
    element: "Air",
    number: 10,
    color: "Faded ivory and quiet grey",
    reflection: "Who are you still keeping a place for — and what would change if you sat in that chair yourself?",
  },
  {
    title: "The First Step",
    theme: "guidance_decision",
    symbol: "A single footprint on a path that has not yet been walked — the rest of the road is still being drawn by the foot that will make it. Behind the print, the ground is smooth, as if no one has ever stood here before.",
    essence: "The first step does not know where the second will land. It steps anyway.",
    element: "Earth",
    number: 2,
    color: "Pale brown with morning light",
    reflection: "What is the smallest thing you could do — that you have been calling too small to count?",
  },
  {
    title: "The Mountain Pass",
    theme: "quiet_strength",
    symbol: "A narrow gap between two peaks, filled with cloud. The rock on either side is scarred by old lightning. Through the pass, faintly, a green valley is visible — but only if you are already walking through.",
    essence: "The mountain does not open for you. You open for it — and the pass was always there.",
    element: "Earth",
    number: 21,
    color: "Iron grey split by distant green",
    reflection: "What passage are you standing before — that only becomes visible once you enter it?",
  },
  {
    title: "The Hidden Spring",
    theme: "hope_abundance",
    symbol: "Dry, cracked earth stretching to the horizon — and then one small patch where water is seeping up, almost invisible. The grass around it is green. A single bird has landed there.",
    essence: "What you need is not gone. It is just not where you are looking — and it has been waiting for you to stop walking.",
    element: "Water",
    number: 4,
    color: "Sand and living green",
    reflection: "If what you were searching for was already beneath your feet — how would you know?",
  },
  {
    title: "The Lantern in Fog",
    theme: "guidance_decision",
    symbol: "Dense fog covering everything — no horizon, no ground line, no sky. A single lantern hangs from a hook that is attached to nothing visible. Its light reaches exactly three steps in every direction.",
    essence: "Three steps of light is enough. It has always been enough.",
    element: "Fire",
    number: 11,
    color: "Soft amber drowning in pearl-white",
    reflection: "If you could only see three steps ahead for the rest of your life — what would you stop waiting for?",
  },
  {
    title: "The Fire That Waits",
    theme: "quiet_strength",
    symbol: "A circle of stones in a forest clearing, wood stacked carefully inside — unlit. The wood is dry. The air smells of sulfur. One match lies on the nearest stone, untouched.",
    essence: "The fire is not absent. It is patient. It knows the difference between 'not yet' and 'never.'",
    element: "Fire",
    number: 15,
    color: "Charcoal black with a red vein",
    reflection: "What are you holding back — that already knows exactly how to burn?",
  },
  {
    title: "The Quiet Return",
    theme: "exhaustion_rest",
    symbol: "A figure walking back along a path they have walked before — but the path has grown over since they left. Wildflowers have filled their old footprints. The house at the end has a candle in the window.",
    essence: "You left so that you could come back. And the place you return to is not the same — because you are not.",
    element: "Water",
    number: 1,
    color: "Dusky rose and homecoming gold",
    reflection: "What part of yourself did you leave behind — that has been growing in your absence?",
  },
  {
    title: "The Sheltering Tree",
    theme: "quiet_strength",
    symbol: "An ancient oak with branches so wide they form a roof — underneath it, the ground is dry and warm, even while rain falls all around. Carved into the trunk, marks from many hands, none of them fresh.",
    essence: "Some things hold without holding on to you.",
    element: "Earth",
    number: 12,
    color: "Deep green and umber",
    reflection: "What has held you — without asking anything in return?",
  },
  {
    title: "The Crossing Stones",
    theme: "guidance_decision",
    symbol: "A shallow river with flat stones breaking the surface — spaced so that each step requires a pause before the next. The water between them is fast and clear. The far bank is close but unreachable in one leap.",
    essence: "The crossing cannot be rushed. Each stone asks for your full weight before it reveals the next.",
    element: "Water",
    number: 3,
    color: "River-grey and moss green",
    reflection: "Which stone are you standing on right now — and what are you pretending is the far bank?",
  },
  {
    title: "The Morning Field",
    theme: "daily_general",
    symbol: "A vast, empty field at dawn — mist rising from the grass, no footprints anywhere, but the dew suggests something walked here moments before. The sky is open in every direction.",
    essence: "The morning does not ask what you will do with it. It simply arrives — and waits to see if you will meet it.",
    element: "Air",
    number: 1,
    color: "Pale gold and silver",
    reflection: "If nothing was yet required of you today, what shape would you choose to move in?",
  },
  {
    title: "The Tended Flame",
    theme: "self_image",
    symbol: "A small candle flame inside a rusted iron lantern, sitting on a wooden table in an otherwise dark room. Outside the window, a storm is visible — but the flame does not flicker.",
    essence: "The flame does not ask the storm to stop. It asks only for enough air to breathe — and for someone to remember it is there.",
    element: "Fire",
    number: 6,
    color: "Amber-orange",
    reflection: "If this flame were the only light you had for the next year — what would you stop doing, just to keep it alive?",
  },
  {
    title: "The Far Shore",
    theme: "hope_abundance",
    symbol: "A shore seen across dark water — no boat, no bridge, but the sand on the other side glows faintly as if lit from beneath. Footprints lead into the water from this side and vanish halfway.",
    essence: "The far shore does not come to you. But something in you is already standing there, waiting for the rest of you to arrive.",
    element: "Water",
    number: 17,
    color: "Deep indigo with a pale sand glow",
    reflection: "If you are already there in some form — what part of you has not yet crossed?",
  },
  {
    title: "The Patient Garden",
    theme: "hope_abundance",
    symbol: "A walled garden seen through a keyhole — inside, plants are growing in spirals, not rows. Some have bloomed. Some are still green stems. One flower faces the keyhole directly, as if it knows someone is looking.",
    essence: "The garden does not know your schedule. It keeps its own time — and it has never once been late.",
    element: "Earth",
    number: 8,
    color: "Moss green behind rusted iron",
    reflection: "What are you rushing — that would bloom on its own if you simply stopped pulling at it?",
  },
  {
    title: "The Open Hand",
    theme: "release_change",
    symbol: "A hand held open, palm up — in it, the faint impression of something that was held for a very long time. The lines of the palm have reshaped around the shape of what is gone. The hand is trembling, but open.",
    essence: "Letting go does not mean it was not precious. It means your hand remembered it was a hand — not a cage.",
    element: "Air",
    number: 9,
    color: "Pale skin-tone washed in grey light",
    reflection: "What have you held so long that your hand has forgotten its own shape?",
  },
  {
    title: "The Still Lake",
    theme: "quiet_strength",
    symbol: "A lake so still that the sky is perfectly reflected in it — but at the edges, small ripples suggest something living just beneath the surface. A single leaf floats at the center, casting no shadow.",
    essence: "Calm is not the absence of depth. It is the surface choosing not to show it.",
    element: "Water",
    number: 14,
    color: "Deep blue-green",
    reflection: "What are you not showing the world — that still moves beneath your stillness?",
  },
  {
    title: "The Northern Star",
    theme: "guidance_decision",
    symbol: "A sky full of moving stars — all shifting, all wheeling — except one. It hangs fixed in the darkest patch of sky, smaller than the rest, but the only one that does not move. A compass on the ground below points toward it, though the compass is cracked.",
    essence: "Not the brightest. Not the closest. The one that does not move when everything else does.",
    element: "Spirit",
    number: 22,
    color: "Ice-white in a field of black",
    reflection: "What is the one thing you know — that does not change, no matter what changes around it?",
  },
  {
    title: "The Threshold",
    theme: "release_change",
    symbol: "A doorway with no walls attached — just a frame standing in the middle of an open field. On one side, sunlight; on the other, shadow. A moth rests on the frame itself, belonging to neither side.",
    essence: "The door does not decide what you become. It only asks you to choose which side you stand on.",
    element: "Spirit",
    number: 10,
    color: "Grey and white, split",
    reflection: "If there were no right or wrong side of this door — which would your feet walk toward?",
  },
  {
    title: "The Gentle Current",
    theme: "release_change",
    symbol: "A paper boat on a slow stream, moving without anyone pushing it. The water is so shallow you can see every stone on the bottom. The boat does not steer — it simply goes where the water already knows to go.",
    essence: "You were never meant to push the river. You were meant to notice it was already moving.",
    element: "Water",
    number: 3,
    color: "Clear water over warm brown stones",
    reflection: "What would happen if you stopped steering — and let the current show you where it was already going?",
  },
  {
    title: "The Watchful Moon",
    theme: "feeling_unseen",
    symbol: "A crescent moon hanging low over a sleeping village — every window dark except one. The moonlight falls only on that window, as if the moon has been watching it all night, waiting for the person inside to look up.",
    essence: "You thought no one saw. But something has been watching you with the patience of the moon — which is to say, it never once looked away.",
    element: "Water",
    number: 18,
    color: "Silver-blue on deep night violet",
    reflection: "If something has been quietly witnessing your life — what moment would you hope it saw?",
  },
  {
    title: "The Climbing Path",
    theme: "guidance_decision",
    symbol: "A steep trail carved into the side of a cliff — narrow, with no railing. Below, clouds. Above, a sky that gets clearer with every step. Halfway up, someone has left a cairn of small stones — a sign that others have passed this way.",
    essence: "The climb does not get easier. You get higher. And from here, the thing that frightened you is the size of a stone.",
    element: "Air",
    number: 19,
    color: "High-altitude blue and raw stone",
    reflection: "What looked enormous from below — that you can barely see from where you stand now?",
  },
  {
    title: "The Quiet Harbor",
    theme: "exhaustion_rest",
    symbol: "A small harbor at evening — boats tied and rocking gently, sails down, no one aboard. The water inside the harbor is still while the sea beyond the breakwall churns. A rope coiled neatly on the dock, waiting for nothing.",
    essence: "Rest is not the absence of storms. It is the knowledge that you do not have to sail in every one.",
    element: "Water",
    number: 2,
    color: "Dusk blue and weathered wood",
    reflection: "What storm have you been sailing in — that you were never asked to cross?",
  },
  {
    title: "The Unopened Letter",
    theme: "hope_abundance",
    symbol: "A sealed envelope on a windowsill, yellowed by sun. The handwriting on the front is your own — but you do not remember writing it. The seal is wax, pressed with a symbol you almost recognize.",
    essence: "There is a message waiting for you — written by someone you used to be, to someone you have not yet become.",
    element: "Air",
    number: 7,
    color: "Parchment yellow and faded ink",
    reflection: "If your past self had written you a letter — what question would it ask about now?",
  },
  {
    title: "The Steady Hands",
    theme: "quiet_strength",
    symbol: "Two hands holding a cracked bowl filled with water — the crack leaks slowly, but the hands are still. They do not grip harder. They do not tilt. They simply hold, and the water that remains is enough.",
    essence: "Strength is not the absence of trembling. It is the bowl still held — even as it leaks.",
    element: "Earth",
    number: 16,
    color: "Clay red and quiet bronze",
    reflection: "What are you holding together — that does not need to be whole to be enough?",
  },
  {
    title: "The Wandering Path",
    theme: "guidance_decision",
    symbol: "A trail that forks, rejoins, forks again — never straight, never lost. Along it, objects left by other travelers: a shoe, a coin, a sketch of a face. None of them are yours, but all of them feel familiar.",
    essence: "The wandering was not the mistake. The mistake was believing the straight line was the only way home.",
    element: "Air",
    number: 5,
    color: "Forest green dappled with moving light",
    reflection: "What did you find on a detour — that you never would have found on the road you planned?",
  },
  {
    title: "The Waiting Dawn",
    theme: "hope_abundance",
    symbol: "The sky one minute before sunrise — the horizon is glowing but the sun has not appeared. The land is still in shadow. A single bird is already singing, as if it can see what you cannot yet.",
    essence: "The dawn does not rush because you are waiting. But it has never, not once, failed to come.",
    element: "Fire",
    number: 1,
    color: "Pre-dawn rose bleeding into night blue",
    reflection: "What would you do differently tonight — if you truly believed the morning was certain?",
  },
  {
    title: "The Deep Well",
    theme: "self_image",
    symbol: "A stone well in a courtyard — no rope, no bucket. Leaning over the edge, you see not water but stars. The well goes down further than the ground should allow. A faint sound rises from it — your own voice, echoing back from a depth you did not know you had.",
    essence: "You have been drawing from the surface. Beneath it, there is something that has never been touched — and it is yours.",
    element: "Water",
    number: 20,
    color: "Midnight blue with scattered starlight",
    reflection: "If you dropped a stone into your own depth — how long would it take to hear it land?",
  },
  {
    title: "The Two Rivers",
    theme: "relationship_tension",
    symbol: "Two rivers meeting at a confluence — one clear, one silted. Where they merge, the water is neither clear nor muddy but a third color entirely. The current at the meeting point is rough, but downstream, it calms into something wider than either river was alone.",
    essence: "Where two waters meet, the turbulence is not the problem. It is the merging — and merging is never still.",
    element: "Water",
    number: 13,
    color: "Two blues becoming a third",
    reflection: "Where in your life are two currents meeting — and what new color are they making?",
  },
  {
    title: "The Shared Fire",
    theme: "relationship_tension",
    symbol: "Two figures sitting on opposite sides of a campfire — their faces lit, their backs in shadow. Between them, the fire casts both their shadows outward in opposite directions. Neither has spoken, but neither has left.",
    essence: "The fire does not ask why you came. It only asks that you both stay long enough to be warm.",
    element: "Fire",
    number: 6,
    color: "Firelight gold and human shadow",
    reflection: "What would you say to the person across the fire — if the silence were not so comfortable?",
  },
  {
    title: "The Distant Bell",
    theme: "feeling_unseen",
    symbol: "A bell tower in fog — the bell is ringing, but the tower is not visible. The sound comes from everywhere and nowhere. On the ground below, people walk past without looking up, though one person has stopped and turned their ear toward the sky.",
    essence: "The bell does not ring for those who hear it clearly. It rings for the one who almost missed it — and turned.",
    element: "Air",
    number: 11,
    color: "Fog-white and tarnished bronze",
    reflection: "What has been calling you — that you have been hearing but pretending is the wind?",
  },
  {
    title: "The Open Window",
    theme: "hope_abundance",
    symbol: "A room you have lived in for years — same walls, same furniture, same light. But today, a window you never noticed is open. The curtain moves. Outside, a landscape you have never seen: hills, water, a sky that is a different blue than the one you know.",
    essence: "The room did not change. A wall you thought was solid had a window in it all along.",
    element: "Air",
    number: 3,
    color: "Interior shadow and exterior blue",
    reflection: "What in your life has been a wall — that might, if you looked closer, be a window?",
  },
  {
    title: "The Roots and the Sky",
    theme: "self_image",
    symbol: "A tree seen from inside the earth — roots spreading like branches into dark soil, mirroring the crown above. Between the two halves, at ground level, the trunk is narrow and scarred. It holds both worlds together without choosing either.",
    essence: "You are not one or the other. You are the trunk — the narrow place where the buried and the reaching meet.",
    element: "Spirit",
    number: 22,
    color: "Earth-brown below, sky-blue above, bark-grey between",
    reflection: "If you are both the roots and the branches — what is the ground you stand on?",
  },
];

const BY_TITLE = new Map(HALO_DECK.map((c) => [c.title.toLowerCase(), c]));
const BY_THEME = HALO_DECK.reduce<Record<string, HaloCard[]>>((acc, c) => {
  (acc[c.theme] ||= []).push(c);
  return acc;
}, {});

/** Exact (case-insensitive) lookup of a deck card by title. */
export function findHalo(title: string | undefined): HaloCard | undefined {
  if (!title) return undefined;
  return BY_TITLE.get(title.trim().toLowerCase());
}

/** All deck cards for a theme (for snapping an off-deck title back onto the deck). */
export function halosForTheme(theme: CardTheme): HaloCard[] {
  return BY_THEME[theme] ?? [];
}

/** The deck rendered for the model, as "Title — essence" lines. */
export function deckListing(): string {
  return HALO_DECK.map((c) => {
    let line = `- ${c.title} — ${c.essence}`;
    if (c.element) line += ` [${c.element}, ${c.number}]`;
    return line;
  }).join("\n");
}
