import type { CardTheme } from "../types";

export type HaloElement = "Fire" | "Water" | "Earth" | "Air" | "Spirit";

export interface HaloCard {
  id: string;
  title: string;
  archetype: string;
  theme: CardTheme;
  symbol: string;
  essence: string;
  shadow: string;
  element: HaloElement;
  number: number;
  color: string;
  themes: string[];
  reflection: string;
}

export const HALO_DECK: HaloCard[] = [
  {
    id: "long_road",
    title: "The Long Road",
    archetype: "Journey",
    theme: "guidance_decision",
    symbol: "A road vanishing into mist. Ahead, faint footprints appear where no one has walked yet.",
    essence: "The path is made by the part of you that keeps moving before certainty arrives.",
    shadow: "A long road can become an excuse to delay beginning.",
    element: "Earth",
    number: 7,
    color: "Grey-green, like stone after rain",
    themes: ["persistence", "patience", "future", "progress"],
    reflection: "What would become possible if you stopped needing the whole road to be visible?",
  },
  {
    id: "open_gate",
    title: "The Open Gate",
    archetype: "Threshold",
    theme: "hope_abundance",
    symbol: "A gate standing alone in a field, with no fence attached.",
    essence: "The gate is not guarding anything. It is asking whether you are ready to pass through.",
    shadow: "An open gate can still feel closed when freedom feels unfamiliar.",
    element: "Air",
    number: 3,
    color: "Pale gold with white",
    themes: ["choice", "permission", "new beginning", "freedom"],
    reflection: "If nothing is blocking you, what are you still waiting for?",
  },
  {
    id: "distant_lantern",
    title: "The Distant Lantern",
    archetype: "Guidance",
    theme: "guidance_decision",
    symbol: "A single lantern at the edge of a dark valley.",
    essence: "You do not need to see the whole road. You only need enough light for the next step.",
    shadow: "A distant light can become something you admire instead of something you walk toward.",
    element: "Fire",
    number: 11,
    color: "Amber",
    themes: ["hope", "direction", "future", "faith"],
    reflection: "If the lantern disappeared, would you still know which way to move?",
  },
  {
    id: "river_keeps_moving",
    title: "The River Keeps Moving",
    archetype: "Surrender",
    theme: "release_change",
    symbol: "A river at night. Leaves and branches drift across its surface without struggling.",
    essence: "The river does not push. It carries.",
    shadow: "Letting go is not the same as abandoning your direction.",
    element: "Water",
    number: 4,
    color: "Deep blue-grey",
    themes: ["flow", "surrender", "acceptance", "release"],
    reflection: "What would you stop fighting if you believed you were already being carried?",
  },
  {
    id: "winter_roots",
    title: "Winter Roots",
    archetype: "Hidden Growth",
    theme: "quiet_strength",
    symbol: "A bare tree in snow. Beneath the frost, roots spread wider than the branches ever did.",
    essence: "What grows most is often what no one sees.",
    shadow: "Invisible growth can feel like failure when you only measure what blooms.",
    element: "Earth",
    number: 9,
    color: "White-grey with brown beneath",
    themes: ["hidden progress", "patience", "resilience", "foundation"],
    reflection: "If you could not see your progress for a year, would you still trust it?",
  },
  {
    id: "sleeping_seed",
    title: "The Sleeping Seed",
    archetype: "Potential",
    theme: "hope_abundance",
    symbol: "A seed buried in dark soil. Above it, morning light begins without the seed seeing it.",
    essence: "What is not visible is not absent.",
    shadow: "Waiting can become numbness if you forget the seed still needs tending.",
    element: "Earth",
    number: 8,
    color: "Deep brown with a thread of gold",
    themes: ["potential", "waiting", "growth", "trust"],
    reflection: "If the seed could speak, would it call itself dead or waiting?",
  },
  {
    id: "gathering_harvest",
    title: "The Gathering Harvest",
    archetype: "Receiving",
    theme: "hope_abundance",
    symbol: "A field of wheat being cut by hands that did not plant it.",
    essence: "What arrives may not come from where you expected.",
    shadow: "Receiving can feel undeserved when you only trust what you earned through struggle.",
    element: "Earth",
    number: 5,
    color: "Gold and amber",
    themes: ["abundance", "receiving", "reward", "timing"],
    reflection: "If the harvest came differently than expected, would you still gather it?",
  },
  {
    id: "turning_door",
    title: "The Turning Door",
    archetype: "Transition",
    theme: "release_change",
    symbol: "A door that seems to open inward and outward at the same time.",
    essence: "Every ending is an opening, but not every opening looks like one.",
    shadow: "A door can keep turning forever if you refuse to choose a side.",
    element: "Spirit",
    number: 10,
    color: "Grey and white, split",
    themes: ["transition", "ending", "beginning", "change"],
    reflection: "What are you leaving behind that you did not know you were carrying?",
  },
  {
    id: "quiet_compass",
    title: "The Quiet Compass",
    archetype: "Inner Direction",
    theme: "guidance_decision",
    symbol: "A compass that does not point north. It points toward something only you can feel.",
    essence: "The direction you need is felt before it is known.",
    shadow: "Inner knowing can be hard to hear when every outside voice sounds urgent.",
    element: "Spirit",
    number: 5,
    color: "Silver and deep blue",
    themes: ["intuition", "direction", "choice", "self-trust"],
    reflection: "If your compass pointed to a place that does not exist yet, would you follow it?",
  },
  {
    id: "last_ember",
    title: "The Last Ember",
    archetype: "Revival",
    theme: "quiet_strength",
    symbol: "One glowing coal in a cold fireplace.",
    essence: "What is almost gone is not yet gone.",
    shadow: "Not every ember is meant to be revived. Some warmth is only memory.",
    element: "Fire",
    number: 2,
    color: "Dark red and ash-grey",
    themes: ["renewal", "memory", "desire", "return"],
    reflection: "If you blew on this ember, what would you be trying to bring back?",
  },
  {
    id: "unfinished_horizon",
    title: "The Unfinished Horizon",
    archetype: "Becoming",
    theme: "hope_abundance",
    symbol: "A horizon that keeps moving as you walk toward it.",
    essence: "The end is not the point. The changing sky is.",
    shadow: "A moving horizon can make arrival impossible if you never define enough.",
    element: "Air",
    number: 15,
    color: "Lavender and grey",
    themes: ["ambition", "becoming", "future", "enough"],
    reflection: "If you never reached the horizon, would you still have traveled?",
  },
  {
    id: "weight_of_becoming",
    title: "The Weight of Becoming",
    archetype: "Growth Burden",
    theme: "release_change",
    symbol: "A figure carrying a stone up a hill.",
    essence: "Growth is not always light. Sometimes it is the weight you choose to carry.",
    shadow: "A burden can become identity when you forget you are allowed to put it down.",
    element: "Earth",
    number: 8,
    color: "Dark grey with a hint of green",
    themes: ["growth", "burden", "discipline", "identity"],
    reflection: "If the stone were lifted from your shoulders, would you know how to stand?",
  },
  {
    id: "bridge_being_built",
    title: "The Bridge Being Built",
    archetype: "Partial Trust",
    theme: "guidance_decision",
    symbol: "Half a bridge stretching over water. The other half is being built by unseen hands.",
    essence: "You do not need the whole bridge to exist before taking the first step.",
    shadow: "Trusting what is unfinished requires knowing when to pause, not only when to leap.",
    element: "Water",
    number: 6,
    color: "Weathered wood and blue",
    themes: ["trust", "transition", "support", "uncertainty"],
    reflection: "What part of the bridge already exists beneath your feet?",
  },
  {
    id: "place_between",
    title: "The Place Between",
    archetype: "Liminality",
    theme: "release_change",
    symbol: "A small island in the middle of a river.",
    essence: "You are not lost. You are between. That is a place too.",
    shadow: "The between can become a hiding place if you stay after the crossing is ready.",
    element: "Water",
    number: 12,
    color: "Mist-grey and pale green",
    themes: ["transition", "uncertainty", "pause", "identity"],
    reflection: "What has this in-between place taught you that arrival could not?",
  },
  {
    id: "path_no_shortcut",
    title: "The Path With No Shortcut",
    archetype: "Discipline",
    theme: "guidance_decision",
    symbol: "A winding staircase where every step is visible and none can be skipped.",
    essence: "Some roads demand every step.",
    shadow: "The wish for a shortcut can make the real path feel unfair.",
    element: "Earth",
    number: 13,
    color: "Stone-grey with moss",
    themes: ["discipline", "process", "effort", "mastery"],
    reflection: "Which step are you trying to skip, and what might it be trying to teach you?",
  },
  {
    id: "light_beyond",
    title: "The Light Beyond",
    archetype: "Hope",
    theme: "hope_abundance",
    symbol: "Warm light coming through a crack in a closed door.",
    essence: "You do not need to see the sun to feel its warmth.",
    shadow: "A glimpse of light is not the same as stepping into it.",
    element: "Fire",
    number: 17,
    color: "Gold and pale yellow",
    themes: ["hope", "possibility", "relief", "future"],
    reflection: "What warmth have you felt before you could explain where it came from?",
  },
  {
    id: "slow_arrival",
    title: "The Slow Arrival",
    archetype: "Timing",
    theme: "exhaustion_rest",
    symbol: "A ship approaching shore so slowly its movement is almost invisible.",
    essence: "Arrival does not look like arrival until it is over.",
    shadow: "Slow movement can be mistaken for no movement at all.",
    element: "Water",
    number: 14,
    color: "Ocean-blue and sand",
    themes: ["timing", "arrival", "patience", "progress"],
    reflection: "Where might you already be arriving without noticing it?",
  },
  {
    id: "orchard",
    title: "The Orchard",
    archetype: "Abundance",
    theme: "hope_abundance",
    symbol: "An orchard heavy with fruit, some of it falling untouched to the ground.",
    essence: "Abundance still needs a hand willing to receive it.",
    shadow: "What is available can still be missed by someone who does not believe they are allowed to take it.",
    element: "Earth",
    number: 10,
    color: "Green and deep red",
    themes: ["abundance", "receiving", "opportunity", "readiness"],
    reflection: "What fruit is already falling near you?",
  },
  {
    id: "returning_tide",
    title: "The Returning Tide",
    archetype: "Return",
    theme: "release_change",
    symbol: "Waves pulling back and returning with what was taken.",
    essence: "Nothing returns exactly as it left.",
    shadow: "Waiting for the old form can make you miss the new one.",
    element: "Water",
    number: 9,
    color: "Blue-grey with white foam",
    themes: ["return", "change", "memory", "cycles"],
    reflection: "If the tide returns differently, will you recognize what it brings?",
  },
  {
    id: "empty_chair",
    title: "The Empty Chair",
    archetype: "Waiting",
    theme: "feeling_unseen",
    symbol: "A chair at a table, set as though someone may arrive.",
    essence: "Waiting is not empty. It is a form of presence.",
    shadow: "A chair kept open too long can become a room no one else may enter.",
    element: "Spirit",
    number: 7,
    color: "Dark wood and candlelight",
    themes: ["absence", "waiting", "belonging", "longing"],
    reflection: "Who or what has been holding a place in you?",
  },
  {
    id: "first_step",
    title: "The First Step",
    archetype: "Beginning",
    theme: "guidance_decision",
    symbol: "One footprint on a path still being drawn by the foot that makes it.",
    essence: "The first step does not know where the second will land. It steps anyway.",
    shadow: "Calling it too small can keep you from beginning at all.",
    element: "Earth",
    number: 2,
    color: "Pale brown with morning light",
    themes: ["beginning", "action", "courage", "small steps"],
    reflection: "What is the smallest thing you could do that you have been calling too small to count?",
  },
  {
    id: "mountain_pass",
    title: "The Mountain Pass",
    archetype: "Challenge",
    theme: "quiet_strength",
    symbol: "A narrow path between two cliffs, wide enough for only one person.",
    essence: "Some passages are narrow. That does not mean they are closed.",
    shadow: "Not everything can come with you through a narrow passage.",
    element: "Earth",
    number: 16,
    color: "Grey stone and sky-blue",
    themes: ["challenge", "focus", "sacrifice", "passage"],
    reflection: "What would you carry if you could only carry one thing forward?",
  },
  {
    id: "hidden_spring",
    title: "The Hidden Spring",
    archetype: "Resource",
    theme: "hope_abundance",
    symbol: "Cracked earth with one small green place where water rises unseen.",
    essence: "What you need is not gone. It may simply not be where you are looking.",
    shadow: "Searching far away can keep you from noticing what is already beneath you.",
    element: "Water",
    number: 4,
    color: "Sand and green",
    themes: ["resource", "renewal", "support", "discovery"],
    reflection: "What might already be beneath your feet?",
  },
  {
    id: "lantern_in_fog",
    title: "The Lantern in Fog",
    archetype: "Uncertain Guidance",
    theme: "guidance_decision",
    symbol: "A lantern held up in thick fog, lighting only a few steps.",
    essence: "The fog does not extinguish the light. It asks you to trust it differently.",
    shadow: "Fog can make you demand certainty from a moment that only offers guidance.",
    element: "Fire",
    number: 7,
    color: "Soft yellow with grey mist",
    themes: ["uncertainty", "guidance", "trust", "next step"],
    reflection: "If you could only see one step ahead, would you still take it?",
  },
  {
    id: "fire_that_waits",
    title: "The Fire That Waits",
    archetype: "Readiness",
    theme: "quiet_strength",
    symbol: "Dry wood stacked for a fire. The match has not yet been struck.",
    essence: "The fire is not impatient. It knows the moment will come.",
    shadow: "Readiness can become restlessness when the spark is delayed.",
    element: "Fire",
    number: 3,
    color: "Ash-grey with a spark of orange",
    themes: ["readiness", "desire", "timing", "potential"],
    reflection: "What in you is ready, even if the moment has not arrived?",
  },
  {
    id: "quiet_return",
    title: "The Quiet Return",
    archetype: "Homecoming",
    theme: "exhaustion_rest",
    symbol: "A path leading back to a house once left, with smoke rising from its chimney.",
    essence: "What you left has not necessarily left you.",
    shadow: "Returning is not the same as becoming who you used to be.",
    element: "Spirit",
    number: 6,
    color: "Evening blue with warm yellow",
    themes: ["return", "identity", "home", "memory"],
    reflection: "What would it mean to return without going backward?",
  },
  {
    id: "sheltering_tree",
    title: "The Sheltering Tree",
    archetype: "Protection",
    theme: "quiet_strength",
    symbol: "An old tree whose wide branches keep the ground dry while rain falls around it.",
    essence: "Some things hold without holding on to you.",
    shadow: "Shelter can become a cage if you forget the rain will pass.",
    element: "Earth",
    number: 12,
    color: "Deep green and umber",
    themes: ["protection", "support", "rest", "safety"],
    reflection: "What has held you without asking anything in return?",
  },
  {
    id: "crossing_stones",
    title: "The Crossing Stones",
    archetype: "Stepwise Passage",
    theme: "guidance_decision",
    symbol: "Flat stones across a stream, each just wide enough for one foot.",
    essence: "The crossing is made one stone at a time.",
    shadow: "Looking too far ahead can make the stone beneath you disappear.",
    element: "Water",
    number: 5,
    color: "Grey and moss-green",
    themes: ["transition", "small steps", "focus", "movement"],
    reflection: "What is the next stone, not the whole crossing?",
  },
  {
    id: "morning_field",
    title: "The Morning Field",
    archetype: "Freshness",
    theme: "daily_general",
    symbol: "An empty field at dawn, covered in mist and unmarked dew.",
    essence: "The morning arrives and waits to see how you will meet it.",
    shadow: "A blank field can feel like freedom or pressure, depending on what you think it demands.",
    element: "Air",
    number: 1,
    color: "Pale gold and silver",
    themes: ["fresh start", "openness", "choice", "beginning"],
    reflection: "If nothing was required of you yet, how would you move?",
  },
  {
    id: "tended_flame",
    title: "The Tended Flame",
    archetype: "Care",
    theme: "self_image",
    symbol: "A small candle inside a rusted lantern while a storm moves outside.",
    essence: "The flame does not ask the storm to stop. It asks to be tended.",
    shadow: "A flame can survive many storms and still be neglected by the one carrying it.",
    element: "Fire",
    number: 6,
    color: "Amber-orange",
    themes: ["care", "energy", "resilience", "protection"],
    reflection: "What would you stop doing if keeping this flame alive mattered most?",
  },
  {
    id: "far_shore",
    title: "The Far Shore",
    archetype: "Destination",
    theme: "hope_abundance",
    symbol: "A shore visible across water too wide to cross in one day.",
    essence: "You will not arrive today, but the shore is real.",
    shadow: "A far shore can become painful when you use it to reject where you are.",
    element: "Water",
    number: 13,
    color: "Grey-blue and white sand",
    themes: ["future", "longing", "destination", "distance"],
    reflection: "How would you live today if you trusted the far shore was real?",
  },
  {
    id: "patient_garden",
    title: "The Patient Garden",
    archetype: "Tending",
    theme: "hope_abundance",
    symbol: "A quiet garden where seeds have been planted but nothing has surfaced.",
    essence: "What does not appear is still happening.",
    shadow: "Tending can become control when you cannot bear the soil's silence.",
    element: "Earth",
    number: 8,
    color: "Dark brown and soft green",
    themes: ["patience", "care", "growth", "timing"],
    reflection: "What are you tending that has not yet answered you?",
  },
  {
    id: "open_hand",
    title: "The Open Hand",
    archetype: "Release",
    theme: "release_change",
    symbol: "An open hand with nothing in it, the fingers relaxed.",
    essence: "Letting go is not losing. It is making room.",
    shadow: "An open hand can still fear what may never arrive.",
    element: "Air",
    number: 5,
    color: "Pale flesh and sunlight",
    themes: ["release", "receiving", "trust", "space"],
    reflection: "What could come into your hand only if it stayed open?",
  },
  {
    id: "still_lake",
    title: "The Still Lake",
    archetype: "Depth",
    theme: "quiet_strength",
    symbol: "A lake so still it reflects the sky, with small ripples near the edge.",
    essence: "Calm is not the absence of depth.",
    shadow: "Stillness can hide what needs to move.",
    element: "Water",
    number: 14,
    color: "Deep blue-green",
    themes: ["calm", "depth", "emotion", "containment"],
    reflection: "What moves beneath your stillness?",
  },
  {
    id: "northern_star",
    title: "The Northern Star",
    archetype: "Steadiness",
    theme: "guidance_decision",
    symbol: "A single star so bright it does not need to move.",
    essence: "Steadiness is the point from which movement is measured.",
    shadow: "Being fixed can become loneliness if you never let yourself be reached.",
    element: "Spirit",
    number: 1,
    color: "Silver and deep indigo",
    themes: ["steadiness", "identity", "orientation", "truth"],
    reflection: "What remains true even when everything else moves?",
  },
  {
    id: "threshold",
    title: "The Threshold",
    archetype: "Decision",
    theme: "release_change",
    symbol: "A doorway with no walls, one side in sunlight and the other in shadow.",
    essence: "The door does not decide what you become. It asks where you will stand.",
    shadow: "Standing at the threshold can feel safer than discovering what is beyond it.",
    element: "Spirit",
    number: 10,
    color: "Grey and white, split",
    themes: ["decision", "transition", "identity", "courage"],
    reflection: "Which side are your feet already leaning toward?",
  },
  {
    id: "gentle_current",
    title: "The Gentle Current",
    archetype: "Soft Progress",
    theme: "release_change",
    symbol: "A slow stream moving toward the sea without urgency.",
    essence: "You do not need to be fast to arrive.",
    shadow: "Gentleness can be mistaken for weakness by the part of you addicted to force.",
    element: "Water",
    number: 4,
    color: "Soft blue and green",
    themes: ["ease", "progress", "gentleness", "trust"],
    reflection: "Where are you demanding speed from something that needs rhythm?",
  },
  {
    id: "watchful_moon",
    title: "The Watchful Moon",
    archetype: "Witness",
    theme: "feeling_unseen",
    symbol: "A full moon over a dark field, illuminating without explaining.",
    essence: "To be seen is sometimes enough.",
    shadow: "Being witnessed can feel like judgment when you are used to hiding.",
    element: "Spirit",
    number: 18,
    color: "Silver-white and deep blue",
    themes: ["visibility", "truth", "witness", "mystery"],
    reflection: "What changes when you let something in you be seen without explaining it?",
  },
  {
    id: "climbing_path",
    title: "The Climbing Path",
    archetype: "Ascent",
    theme: "guidance_decision",
    symbol: "A path rising upward until its top disappears into clouds.",
    essence: "The reward is not only the top. It is the view gained with each step.",
    shadow: "The climb can consume you if you forget to look around.",
    element: "Earth",
    number: 11,
    color: "Stone and sky",
    themes: ["ambition", "effort", "growth", "perspective"],
    reflection: "What view have you already earned from where you stand?",
  },
  {
    id: "quiet_harbor",
    title: "The Quiet Harbor",
    archetype: "Rest",
    theme: "exhaustion_rest",
    symbol: "A harbor at dusk. Boats are tied, the water is still, and no one is leaving.",
    essence: "Rest is not waiting. Rest is a destination.",
    shadow: "A harbor can protect you from the sea and from your own next voyage.",
    element: "Water",
    number: 14,
    color: "Soft blue and warm wood",
    themes: ["rest", "safety", "pause", "recovery"],
    reflection: "If rest were the destination, what would change?",
  },
  {
    id: "unopened_letter",
    title: "The Unopened Letter",
    archetype: "Message",
    theme: "hope_abundance",
    symbol: "A sealed envelope on a wooden table with no return address.",
    essence: "What you have not yet read is still a message.",
    shadow: "Not opening the letter can become a way of keeping every possibility alive.",
    element: "Air",
    number: 8,
    color: "Cream and faded gold",
    themes: ["truth", "avoidance", "message", "curiosity"],
    reflection: "What truth have you kept sealed because it might change you?",
  },
  {
    id: "steady_hands",
    title: "The Steady Hands",
    archetype: "Precision",
    theme: "quiet_strength",
    symbol: "Two hands holding a feather so still it does not move in the wind.",
    essence: "Steadiness is not always strength. Sometimes it is precision.",
    shadow: "Holding too carefully can become another form of fear.",
    element: "Air",
    number: 4,
    color: "Warm skin and soft white",
    themes: ["care", "focus", "control", "steadiness"],
    reflection: "What are you holding so carefully that it cannot breathe?",
  },
  {
    id: "wandering_path",
    title: "The Wandering Path",
    archetype: "Exploration",
    theme: "guidance_decision",
    symbol: "A path that curves and loops back without ending.",
    essence: "Not all wandering is lost. Some wandering is the path itself.",
    shadow: "Wandering can become avoidance when you know the road you are refusing.",
    element: "Earth",
    number: 9,
    color: "Brown and green with touches of red",
    themes: ["exploration", "uncertainty", "purpose", "search"],
    reflection: "Where might wandering be wiser than forcing direction?",
  },
  {
    id: "waiting_dawn",
    title: "The Waiting Dawn",
    archetype: "Almost Light",
    theme: "hope_abundance",
    symbol: "The sky just before sunrise, no longer dark but not yet bright.",
    essence: "The waiting is not empty. It is the edge of something new.",
    shadow: "Almost-light can feel cruel when you have been waiting too long.",
    element: "Fire",
    number: 1,
    color: "Deep blue with a thread of gold",
    themes: ["anticipation", "hope", "beginning", "timing"],
    reflection: "What would you do differently if you believed morning had already begun?",
  },
  {
    id: "deep_well",
    title: "The Deep Well",
    archetype: "Inner Resource",
    theme: "self_image",
    symbol: "A stone well in a field, its water too deep to see.",
    essence: "What you need may be deeper than you are used to reaching.",
    shadow: "Depth can be avoided by pretending the surface is enough.",
    element: "Earth",
    number: 6,
    color: "Grey stone and cool green",
    themes: ["resource", "depth", "inner strength", "need"],
    reflection: "What would you ask for if you trusted the well was not dry?",
  },
  {
    id: "two_rivers",
    title: "The Two Rivers",
    archetype: "Divergence",
    theme: "relationship_tension",
    symbol: "Two rivers flowing side by side, sometimes close, never the same.",
    essence: "You cannot merge two rivers without changing both.",
    shadow: "Trying to keep every path alive can keep any one path from deepening.",
    element: "Water",
    number: 2,
    color: "Two shades of blue",
    themes: ["choice", "relationship", "divergence", "difference"],
    reflection: "If you had to choose one river, which would you miss?",
  },
  {
    id: "shared_fire",
    title: "The Shared Fire",
    archetype: "Belonging",
    theme: "relationship_tension",
    symbol: "Two figures sitting by one fire without speaking.",
    essence: "Belonging is not always words. Sometimes it is shared warmth.",
    shadow: "Sharing warmth can still leave parts of you unseen.",
    element: "Fire",
    number: 6,
    color: "Orange and shadow",
    themes: ["belonging", "connection", "presence", "warmth"],
    reflection: "Who feels like warmth without needing explanation?",
  },
  {
    id: "distant_bell",
    title: "The Distant Bell",
    archetype: "Calling",
    theme: "feeling_unseen",
    symbol: "A bell tower too far to see, but close enough to hear.",
    essence: "Some calls are meant to be heard before they are seen.",
    shadow: "A distant call can become haunting if you never answer it.",
    element: "Air",
    number: 7,
    color: "Faded grey and pale blue",
    themes: ["calling", "intuition", "attention", "future"],
    reflection: "What keeps calling even when you try not to listen?",
  },
  {
    id: "open_window",
    title: "The Open Window",
    archetype: "Perspective",
    theme: "hope_abundance",
    symbol: "A window open to the night, its curtain moving though there is no wind.",
    essence: "A new way of seeing the same room is still new.",
    shadow: "A window is not an exit unless you choose to move toward it.",
    element: "Air",
    number: 3,
    color: "Dark blue and pale yellow",
    themes: ["perspective", "possibility", "awareness", "openness"],
    reflection: "What changes if you look at the same room from a different opening?",
  },
  {
    id: "roots_and_sky",
    title: "The Roots and the Sky",
    archetype: "Integration",
    theme: "self_image",
    symbol: "A tree whose roots reach as deep as its branches rise high.",
    essence: "You are not only who you have been, nor only who you are becoming. You are both.",
    shadow: "Reaching upward without roots can make growth feel like escape.",
    element: "Earth",
    number: 22,
    color: "Deep brown and pale blue",
    themes: ["identity", "integration", "growth", "belonging"],
    reflection: "Which part of you needs more trust: the roots or the sky?",
  },
  {
    id: "cracked_mirror",
    title: "The Cracked Mirror",
    archetype: "Distorted Seeing",
    theme: "self_image",
    symbol: "A mirror split by one clean crack. Every piece still reflects the same face differently.",
    essence: "Sometimes what breaks is the image, not the self.",
    shadow: "You may be mistaking one distorted reflection for the whole truth.",
    element: "Air",
    number: 19,
    color: "Silver with a dark fracture",
    themes: ["self-image", "truth", "distortion", "identity"],
    reflection: "Which reflection have you been treating as the only one?",
  },
  {
    id: "closed_fist",
    title: "The Closed Fist",
    archetype: "Protection",
    theme: "quiet_strength",
    symbol: "A clenched hand holding something unseen. No one can take it, but nothing can enter.",
    essence: "What protects you may also prevent you from receiving.",
    shadow: "Control can become a wall you mistake for safety.",
    element: "Earth",
    number: 4,
    color: "Deep umber and muted gold",
    themes: ["control", "protection", "receiving", "fear"],
    reflection: "What are you protecting so tightly that it can no longer breathe?",
  },
  {
    id: "burned_map",
    title: "The Burned Map",
    archetype: "Lost Direction",
    theme: "release_change",
    symbol: "A map burned at the center. The edges remain, but the destination is gone.",
    essence: "Some directions disappear so another way can emerge.",
    shadow: "You may still be trying to follow a map that no longer knows you.",
    element: "Fire",
    number: 16,
    color: "Charcoal, ash, and burnt orange",
    themes: ["change", "lost plans", "reinvention", "release"],
    reflection: "If the old map cannot take you there, what part of you already knows another way?",
  },
  {
    id: "empty_nest",
    title: "The Empty Nest",
    archetype: "Departure",
    theme: "release_change",
    symbol: "A nest on a branch after the birds have gone. It is empty, but still carefully made.",
    essence: "Not everything that leaves was taken from you.",
    shadow: "An empty place can become sacred or bitter, depending on how you hold it.",
    element: "Air",
    number: 12,
    color: "Soft brown and pale sky",
    themes: ["loss", "release", "maturity", "change"],
    reflection: "What has left because it was ready, not because you failed to keep it?",
  },
  {
    id: "storm_crossing",
    title: "The Storm Crossing",
    archetype: "Discomfort",
    theme: "quiet_strength",
    symbol: "A narrow bridge under heavy rain. The other side is visible, but the crossing is loud.",
    essence: "Some crossings cannot happen without discomfort.",
    shadow: "Waiting for calm may become the reason you never cross.",
    element: "Water",
    number: 18,
    color: "Storm blue and white lightning",
    themes: ["discomfort", "courage", "transition", "fear"],
    reflection: "What are you waiting to feel ready for, when the crossing itself may create readiness?",
  },
  {
    id: "black_sun",
    title: "The Black Sun",
    archetype: "Hidden Power",
    theme: "self_image",
    symbol: "A dark sun above a pale landscape, giving no light but still pulling everything toward it.",
    essence: "Power is not always bright.",
    shadow: "What you refuse to name may be shaping the room more than what you admit.",
    element: "Spirit",
    number: 20,
    color: "Black, bronze, and pale cream",
    themes: ["shadow", "power", "truth", "unconscious"],
    reflection: "What has power in you because it has not yet been named?",
  },
  {
    id: "broken_bowl",
    title: "The Broken Bowl",
    archetype: "Capacity",
    theme: "exhaustion_rest",
    symbol: "A ceramic bowl with one missing piece. Water leaks slowly from the side.",
    essence: "You cannot hold what you keep losing through the place you refuse to mend.",
    shadow: "Giving more will not help if the vessel itself needs care.",
    element: "Water",
    number: 6,
    color: "Porcelain white and soft blue",
    themes: ["capacity", "care", "leakage", "boundaries"],
    reflection: "Where are you trying to receive more before repairing what cannot hold it?",
  },
  {
    id: "locked_room",
    title: "The Locked Room",
    archetype: "Avoided Truth",
    theme: "self_image",
    symbol: "A locked room at the end of a bright hallway. The key is already in the door.",
    essence: "What is locked is not always inaccessible.",
    shadow: "Sometimes the door stays closed because opening it would make pretending impossible.",
    element: "Spirit",
    number: 9,
    color: "Warm white and old brass",
    themes: ["avoidance", "truth", "readiness", "secrecy"],
    reflection: "What door have you kept locked because you already know where the key is?",
  },
  {
    id: "thorned_crown",
    title: "The Thorned Crown",
    archetype: "Cost of Status",
    theme: "self_image",
    symbol: "A crown woven with thorns, beautiful from far away and painful up close.",
    essence: "Not every victory is gentle to wear.",
    shadow: "You may be reaching for something without asking what it will ask of you.",
    element: "Fire",
    number: 15,
    color: "Gold, crimson, and dark green",
    themes: ["ambition", "status", "cost", "desire"],
    reflection: "What prize do you want, and what part of you would have to wear it?",
  },
  {
    id: "silent_room",
    title: "The Silent Room",
    archetype: "Unspoken Truth",
    theme: "relationship_tension",
    symbol: "A room full of chairs, all facing inward. No one speaks, but everyone is listening.",
    essence: "Silence is not always absence. Sometimes it is everything waiting to be said.",
    shadow: "What is unspoken can become louder than words.",
    element: "Air",
    number: 10,
    color: "Dusty rose and shadow grey",
    themes: ["silence", "truth", "communication", "tension"],
    reflection: "What has become louder because no one has said it?",
  },
];

const BY_TITLE = new Map(HALO_DECK.map((c) => [c.title.toLowerCase(), c]));
const BY_ID = new Map(HALO_DECK.map((c) => [c.id, c]));
const BY_THEME = HALO_DECK.reduce<Record<string, HaloCard[]>>((acc, c) => {
  (acc[c.theme] ||= []).push(c);
  return acc;
}, {});

/** Exact (case-insensitive) lookup of a deck card by title. */
export function findHalo(title: string | undefined): HaloCard | undefined {
  if (!title) return undefined;
  return BY_TITLE.get(title.trim().toLowerCase());
}

/** Lookup by card id. */
export function findHaloById(id: string | undefined): HaloCard | undefined {
  if (!id) return undefined;
  return BY_ID.get(id);
}

/** All deck cards for a theme (for snapping an off-deck title back onto the deck). */
export function halosForTheme(theme: CardTheme): HaloCard[] {
  return BY_THEME[theme] ?? [];
}

/** The deck rendered for the model — includes title, archetype, essence, shadow, and themes. */
export function deckListing(): string {
  return HALO_DECK.map((c) =>
    `- ${c.title} (${c.archetype}) [${c.element}] — ${c.essence} | Shadow: ${c.shadow} | Themes: ${c.themes.join(", ")}`
  ).join("\n");
}
