/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SupportRouteImport } from './routes/support'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SavedRouteImport } from './routes/saved'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PaywallRouteImport } from './routes/paywall'
import { Route as GoalRouteImport } from './routes/goal'
import { Route as CalendarRouteImport } from './routes/calendar'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SparkTokenRouteImport } from './routes/spark.$token'

const SupportRoute = SupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SavedRoute = SavedRouteImport.update({
  id: '/saved',
  path: '/saved',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PaywallRoute = PaywallRouteImport.update({
  id: '/paywall',
  path: '/paywall',
  getParentRoute: () => rootRouteImport,
} as any)
const GoalRoute = GoalRouteImport.update({
  id: '/goal',
  path: '/goal',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarRoute = CalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SparkTokenRoute = SparkTokenRouteImport.update({
  id: '/spark/$token',
  path: '/spark/$token',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/calendar': typeof CalendarRoute
  '/goal': typeof GoalRoute
  '/paywall': typeof PaywallRoute
  '/privacy': typeof PrivacyRoute
  '/saved': typeof SavedRoute
  '/settings': typeof SettingsRoute
  '/support': typeof SupportRoute
  '/spark/$token': typeof SparkTokenRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/calendar': typeof CalendarRoute
  '/goal': typeof GoalRoute
  '/paywall': typeof PaywallRoute
  '/privacy': typeof PrivacyRoute
  '/saved': typeof SavedRoute
  '/settings': typeof SettingsRoute
  '/support': typeof SupportRoute
  '/spark/$token': typeof SparkTokenRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/calendar': typeof CalendarRoute
  '/goal': typeof GoalRoute
  '/paywall': typeof PaywallRoute
  '/privacy': typeof PrivacyRoute
  '/saved': typeof SavedRoute
  '/settings': typeof SettingsRoute
  '/support': typeof SupportRoute
  '/spark/$token': typeof SparkTokenRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/calendar'
    | '/goal'
    | '/paywall'
    | '/privacy'
    | '/saved'
    | '/settings'
    | '/support'
    | '/spark/$token'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/calendar'
    | '/goal'
    | '/paywall'
    | '/privacy'
    | '/saved'
    | '/settings'
    | '/support'
    | '/spark/$token'
  id:
    | '__root__'
    | '/'
    | '/calendar'
    | '/goal'
    | '/paywall'
    | '/privacy'
    | '/saved'
    | '/settings'
    | '/support'
    | '/spark/$token'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CalendarRoute: typeof CalendarRoute
  GoalRoute: typeof GoalRoute
  PaywallRoute: typeof PaywallRoute
  PrivacyRoute: typeof PrivacyRoute
  SavedRoute: typeof SavedRoute
  SettingsRoute: typeof SettingsRoute
  SupportRoute: typeof SupportRoute
  SparkTokenRoute: typeof SparkTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/support': {
      id: '/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof SupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/saved': {
      id: '/saved'
      path: '/saved'
      fullPath: '/saved'
      preLoaderRoute: typeof SavedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/paywall': {
      id: '/paywall'
      path: '/paywall'
      fullPath: '/paywall'
      preLoaderRoute: typeof PaywallRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/goal': {
      id: '/goal'
      path: '/goal'
      fullPath: '/goal'
      preLoaderRoute: typeof GoalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendar': {
      id: '/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof CalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/spark/$token': {
      id: '/spark/$token'
      path: '/spark/$token'
      fullPath: '/spark/$token'
      preLoaderRoute: typeof SparkTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CalendarRoute: CalendarRoute,
  GoalRoute: GoalRoute,
  PaywallRoute: PaywallRoute,
  PrivacyRoute: PrivacyRoute,
  SavedRoute: SavedRoute,
  SettingsRoute: SettingsRoute,
  SupportRoute: SupportRoute,
  SparkTokenRoute: SparkTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
